### ISSUE TITLE
Forum threads in categories are sorted from old to new

### ISSUE THREAD

**Issue by wilco375** [csvalpha/amber-ui#125]
It seems more logical to me that the most recently updated forum thread is on top and the oldest one on the bottom in on the category page, but the forum thread with the latest update is shown last now.

**Comment by Matthijsy** [comment]
This is actually sinds it reads more easily, if you want to start reading a forum topic it is logical to start at the beginning not at the and. Also the 'new' field is now close to the last message

**Comment by wilco375** [comment]
Sorry, I meant categories, not topics
So the page /forum/categories/{id}/threads

**Comment by Matthijsy** [comment]
Ah that makes more sense, yes the newest should be the first in that case

**Comment by DrumsnChocolate** [comment]
what's the status on this?

**Comment by wilco375** [comment]
Still not resolved. I tried to locate the problem but couldn't find it filter/search is also broken on this page.

**Comment by DrumsnChocolate** [comment]
let me know if you want me to try and look at it

**Comment by wilco375** [comment]
Sure, go ahead
