### ISSUE TITLE
picture x of y indicator broken

### ISSUE THREAD

**Issue by Matthijsy** [csvalpha/amber-ui#13]
### How to reproduce
1. Go to a photo in a album
2. Check the title 'x van y'

### Expected behaviour
The x is increased by 1 every time you go to the next image

### Current behaviour
x stays always 1

**Comment by cmitz** [comment]
I think this is only possible by rethinking how we show a photoalbum.

I don't think every photo should have it's own page. Maybe just have a viewer on the album.show page, capable of displaying individual images?

**Comment by Matthijsy** [comment]
Probably it is just a computed property with an incorrect listener. I think that every photo on a single page is useful since the have their own link so you can link to them

**Comment by guidojw** [comment]
It looks like this fixed itself. It's showing the correct photo numbers for me now.

**Comment by Matthijsy** [comment]
Agreed, works at my machine as well
