### ISSUE TITLE
Editing forum post not working

### ISSUE THREAD

**Issue by Matthijsy** [csvalpha/amber-ui#131]
### How to reproduce
1. Go to forum
1. Edit a post

### Expected behaviour
It works

### Current behaviour
A 422 is returned, no error message is shown. But the issue is that no thread is attached in the request.

So 2 things needs to be fixed, the error display and the update itself.

Probably related: https://sentry.io/organizations/csvalpha/issues/1567059011/?project=185615&referrer=slack

**Comment by wilco375** [comment]
I don't have any problems editing forum posts?

**Comment by Matthijsy** [comment]
Weird, it now also works for myself. So probably already fixed.
