### ISSUE TITLE
Daily verse is broken

### ISSUE THREAD

**Issue by wilco375** [csvalpha/amber-ui#144]
### How to reproduce
Go to the homepage while logged in 

### Expected behaviour
Daily verse shows up

### Current behaviour
Daily verse doesn't show up

### What goes wrong
A request is made to https://csvalpha.nl/api/v1/daily_verses but the correct endpoint is https://csvalpha.nl/api/v1/daily_verse

**Comment by Matthijsy** [comment]
Is this an UI issue in that case, because I think /daily_verses is the correct endpoint. We also retrieve the users via /users.

**Comment by wilco375** [comment]
In that case, I will move it to API
