### ISSUE TITLE
Show a notification to install the Sponsorkliks extension

### ISSUE THREAD

**Issue by wilco375** [csvalpha/amber-ui#155]
We can now detect if the Sponsorkliks extension is installed because it adds the `data-sponsorkliks-extension="1"` property to the `html` tag of the website. So it would be nice to add a notification to the website somewhere on the homepage for logged in users that asks them to install the Sponsorkliks extension if it is not installed yet. Because it is basically free money for Alpha :smiley:

**Comment by Matthijsy** [comment]
Already in PR https://github.com/csvalpha/amber-ui/pull/153 :) Would be nice to get a review

**Comment by wilco375** [comment]
Ah nice, we had the same thought
