### ISSUE TITLE
Changing password as member not possible

### ISSUE THREAD

**Issue by RubenSmit** [csvalpha/amber-ui#19]
### How to reproduce
As a member, go to your profile

### Expected behaviour
There is a 'beveiliging' tab allowing you to change your password
![Capture](https://user-images.githubusercontent.com/5909658/57250556-037d2480-7048-11e9-9797-cd9f2f995e0b.PNG)

### Current behaviour
There is no option to change your password.
![Capture](https://user-images.githubusercontent.com/5909658/57250644-3e7f5800-7048-11e9-9fb4-8a522499bbbc.PNG)

### Notes
The 'beveiliging' tab is available for members of the ict committee somehow.

**Comment by RubenSmit** [comment]
Ik heb zojuist gepoogd dit te fixen, maar dit probleem doet zich niet voor op de staging omgeving, en ik weet niet of het nog bestaat. We zouden even een gebruiker moeten lenen om dit te testen.

**Comment by cpbscholten** [comment]
I cannot reroduce this issue, we can reopen this if it occurs again
