### ISSUE TITLE
Extend full day activity warning

### ISSUE THREAD

**Issue by Matthijsy** [csvalpha/amber-ui#208]
### How to reproduce
1. Create an activity that is one day and starts at 00:00 and ends at 23:59

### Expected behaviour
I would expect that I see the warning that it should end at 00:00 the next day

### Current behaviour
Since this activity is not more than 1 day the warning is not shown, resulting in incorrect ical entries

**Comment by wilco375** [comment]
So where would you draw the line when and when not to show this warning?

**Comment by Matthijsy** [comment]
I think if it is more than 1 day, or when the activity starts on 00:00 and ends on 23:59, since that is what I as end user would call a full-day activity. All other start/end time combinations are not logical when trying to create a full-day activity
