### ISSUE TITLE
Activity registration error

### ISSUE THREAD

**Issue by DrumsnChocolate** [csvalpha/amber-ui#243]
### How to reproduce (tested logged in as the user 'lid')
1. Create an activity with a registration list
2. Register for the activity

### Expected behaviour
If the registration input information is valid, the user should see a confirmation of registration for the activity, without errors.

### Current behaviour
After clicking the registration button for an activity, the following error is displayed:
![image](https://user-images.githubusercontent.com/32799956/99915736-bf26a780-2d05-11eb-9dc0-37691c15c56a.png)
In this specific screenshot, the user is also not yet listed in the list of registered participants. This may or may not be consistent behaviour, haven't checked that part. What is consistent, however, is that an error's displayed.
After refreshing the activity page, the following is shown:
![image](https://user-images.githubusercontent.com/32799956/99915740-c948a600-2d05-11eb-84f3-d9a08881fce9.png)

**Comment by Matthijsy** [comment]
To fix this probably the flashNotice service should be injected into the controller/component
