### ISSUE TITLE
Group member tabs appear incorrectly on mobile version

### ISSUE THREAD

**Issue by guidojw** [csvalpha/amber-ui#27]
### How to reproduce
Go to any group page on the mobile version.
(I use Chrome on Android 8.0.0)

### Expected behaviour
The tabs should appear in the white container, like on the desktop version.
![image](https://user-images.githubusercontent.com/35309288/58078056-1ea27500-7bae-11e9-8d55-47c86ac85f3d.png)

### Current behaviour
The tabs appear too high.
![image](https://user-images.githubusercontent.com/35309288/58078095-3974e980-7bae-11e9-987b-64c487b93f5c.png)

**Comment by cmitz** [comment]
We're aware, was fixed in PR #23 but that PR still requires some work
