### ISSUE TITLE
Navigating through polls doesn't work

### ISSUE THREAD

**Issue by wilco375** [csvalpha/amber-ui#272]
### How to reproduce
1. Go to a poll
2. Click on polls in the breadcrumb or menu to go back to the overview
3. Go to another poll

### Expected behaviour
The poll is shown

### Current behaviour
An error is thrown
![image](https://user-images.githubusercontent.com/7385023/109293698-7282c900-782c-11eb-8eb5-3d6da82848a8.png)

**Comment by Matthijsy** [comment]
Probably related to https://github.com/csvalpha/amber-ui/issues/250
