### ISSUE TITLE
OAuth authorize route auto invalidates session when logging in before authorizing

### ISSUE THREAD

**Issue by guidojw** [csvalpha/amber-ui#281]
With #274 you now get redirected to the login page if you're not authenticated but the rest still goes wrong.

### How to reproduce
1. Go to streep.csvalpha.nl when not logged in on csvalpha.nl
2. Click "Sign in with C.S.V. Alpha"
3. Login on the main site

### Expected behaviour
It should redirect you to streep.csvalpha.nl where you are now logged in.

### Current behaviour
You get redirected to the public page of csvalpha.nl where you're still logged out.

After looking through the network requests of my browser console, I found this:
![Screenshot_1547](https://user-images.githubusercontent.com/35309288/109434573-39a64800-7a16-11eb-9c3e-ddde38549ffb.png)

A request that's missing here but is executed when authorizing SOFIA from a logged in account is GET /users/:id/permissions, executed by [this line](https://github.com/csvalpha/amber-ui/blob/64e18bc883a4cee73d8243479c60858e4690071c/app/services/session.js#L34).
I'm not sure why this line isn't being executed but it probably causes the loadUser method to throw which then automatically [invalidates the session](https://github.com/csvalpha/amber-ui/blob/64e18bc883a4cee73d8243479c60858e4690071c/app/services/session.js#L22) (last 2 requests in the screenshot).

**Comment by Matthijsy** [comment]
If you did not yet authorize the application it still works. Maybee it has something to do with this line, since that one is executed, and does something else when already authorized or not authorized: https://github.com/csvalpha/amber-ui/blob/staging/app/routes/oauth/authorize.js#L27
