### ISSUE TITLE
Mailing enrolled users for activities not possible

### ISSUE THREAD

**Issue by RubenSmit** [csvalpha/amber-ui#296]
### How to reproduce
1. Navigate to a activity with enrolled users for which the enrollment period has ended.
2. Press the "mail enrolled" button

### Expected behaviour
A prompt allowing the user to compose an email should appear.

### Current behaviour
An error page appears with `TypeError: e is null`.

**Comment by lodewiges** [comment]
unable to reproduce ![Image](https://github.com/user-attachments/assets/75ca4dea-624a-45f2-b762-a7b0c4332ca8)

**Comment by RubenSmit** [comment]
Lol, so I made this ticket a while ago but it is not relevant anymore since the functionality is not present in the current version of the application. I will close this issue.
