### ISSUE TITLE
Formatting text does not work

### ISSUE THREAD

**Issue by FeijevanAbbema** [csvalpha/amber-ui#308]
### How to reproduce
1. Go to a place where you can write some text with formatting (forum post for example)
2. Try to insert some formatting (for example bold, hyperlink)

### Expected behaviour
Text will appear that will create the formatting

### Current behaviour
Nothing happens

**Comment by wilco375** [comment]
Adding `@tracked` to the content property in md-editor.js fixes the updating of the textarea. However, after doing this the parent property is no longer updated when `content` changes, so input changes will be discarded after saving. @Matthijsy any idea on how to fix this? My knowledge of Ember is lacking here.

**Comment by Matthijsy** [comment]
I think I remember this as a issue I encountered earlier. I think we have to update the components to octane style first to fix this issue

**Comment by guidojw** [comment]
Yeah, reference: https://github.com/csvalpha/amber-ui/pull/280#discussion_r587691233
