### ISSUE TITLE
Cannot view image tool as old member

### ISSUE THREAD

**Issue by Matthijsy** [csvalpha/amber-ui#345]
### How to reproduce
1. Go to the homepage
2. Search for the image tool

### Expected behaviour
Since 'oud-leden' have permissions to view the images I would expect we can see the tool as well. We don't have permissions to see the comments, so the comments part of the tool should be hidden.

### Current behaviour
The complete tool is hidden

**Comment by DrumsnChocolate** [comment]
To my knowledge, 'oud-leden' don't normally have permissions to view images. It is debatable whether this lack of permissions related to viewing images is appropriate, and we've opened an API issue related to this: https://github.com/csvalpha/amber-api/issues/250
