### ISSUE TITLE
Sepa export is broken

### ISSUE THREAD

**Issue by DrumsnChocolate** [csvalpha/amber-ui#376]
Export a (valid) debit collection, expected behaviour is that an XML file will be downloaded.
Instead, the following message is shown:
![image](https://user-images.githubusercontent.com/32799956/142026883-8e1fbfc2-86af-494f-8565-2dbd75026091.png)

Current workaround is to refresh the page, and suddenly you are prompted with the XML file.

**Comment by guidojw** [comment]
Not sure if it fixes this, but https://github.com/csvalpha/amber-ui/pull/369 changes some filesaver related stuff in the sepa controller.

**Comment by DrumsnChocolate** [comment]
I checked, and it does not fix it. I think it has to do with the route model hook not being run when transitioning from debit.collection.show to debit.collection.sepa

**Comment by DrumsnChocolate** [comment]
This seems to be due to the fact that page-action.hbs provides pageAction.linkArgument as @model to the LinkTo component. The linkArgument for the download sepa action is specified in route debit.collection.show to be a collection object. This is apparently intended behaviour: https://guides.emberjs.com/release/routing/linking-between-routes/#toc_the-linkto--component
I believe I have come across a similar issue before, and it's quite a sneaky bug.
