### ISSUE TITLE
Two factor authentication code is not shown correctly

### ISSUE THREAD

**Issue by wilco375** [csvalpha/amber-ui#42]
### How to reproduce
1. Go to account security settings
2. Click enable two factor authentication

### Expected behaviour
The website should show a QR-code to scan with an Authenticator app

### Current behaviour
The QR-code is not shown

### Screenshots
![image](https://user-images.githubusercontent.com/7385023/65499233-97e40880-debd-11e9-8cac-60104a3d90d7.png)
![image](https://user-images.githubusercontent.com/7385023/65499280-a5998e00-debd-11e9-8975-201ff2696816.png)

**Comment by Matthijsy** [comment]
Fixed in #68
