### ISSUE TITLE
Feature: swiping in photo albums

### ISSUE THREAD

**Issue by DrumsnChocolate** [csvalpha/amber-ui#424]
### How to reproduce
Go to a foto album, click on a photo

### Desired behaviour
Swiping left and right on mobile should work similarly to pressing left and right arrow keys on desktop, redirecting to next or previous image in album.

### Current behaviour
Swiping doesn't do a thing

**Comment by guidojw** [comment]
https://github.com/Ember-Swiper/ember-cli-swiper this looks cool, doesn't look too maintained though.

**Comment by DrumsnChocolate** [comment]
I don't think it needs animation, so it might be simpler to use touch events on HTML. We should be able to write a generic Swipable component using touchstart, touchmove, touched and touchcancel, I think: https://developer.mozilla.org/en-US/docs/Web/API/TouchEvent
