### ISSUE TITLE
Relations not loaded correctly (Staging)

### ISSUE THREAD

**Issue by cmitz** [csvalpha/amber-ui#49]
### How to reproduce
1. Go to a group
1. Or go to an article

### Current behaviour
Memberships of groups are not shown, article reactions are not shown.

**Comment by cmitz** [comment]
In the (Ember) adapter, links of relationships are removed because Rails JSON::API-Resources provides bad URL's.

This is on purpose, but might be the cause of this bug. Ember should (and did as far as I tested) load relationships the old-fashioned way if there is no linkage data.

**Comment by cpbscholten** [comment]
Not a problem anymore

**Comment by cmitz** [comment]
Was fixed in #56
