### ISSUE TITLE
Quickpost

### ISSUE THREAD

**Issue by cmitz** [csvalpha/amber-ui#50]
The Quickpost could use a refactor. We should refactor to Actioncable, but also refactor the way messages are loaded in the frontend.

**Comment by Matthijsy** [comment]
I am actually not sure if we should migrate to actioncable. Since actioncable uses websockets and this needs more configuration (like special webserver, redis config etc). What is wrong with the current messagebus system? (except that ember is revoking the session due to this)

**Comment by cmitz** [comment]
> What is wrong with the current messagebus system?

- Hard to debug
- Hard to hook into ember
- Not an NPM package so in vendor folder
- Does complicated stuff with channels that we don't need

**However** I played around with ActionCable last week and it lacks authorization (because Websocket does not have HTTP headers) and it is not easier to work with than messagebus.

So, when thinking about ActionCable it is easier to just fire events over the websocket to make Ember fetch the new data itself. Somethink like the 'notify-observers' pattern.

Either way, long-polling is not a bad technique.

**Comment by Matthijsy** [comment]
Maybe we could use pusher (https://pusher.com/chatkit/pricing) for the job. Could be a bit overkill, but does the job and works with ember (https://blog.pusher.com/real-time-chat-with-ember-2-and-pusher/).

**Comment by lodewiges** [comment]
quickpost has been deleted, closing this issue
