### ISSUE TITLE
Dropdown input no longer accessible on group page

### ISSUE THREAD

**Issue by DrumsnChocolate** [csvalpha/amber-ui#540]
Previously, when visiting the /groups route, there would be a dropdown, allowing easy selection of the type of group. This dropdown has disappeared/is no longer accessible.

**Comment by guidojw** [comment]
This? 
![image](https://user-images.githubusercontent.com/35309288/167861703-0d7505e9-741c-4ff0-acd3-7529ef261644.png)

**Comment by guidojw** [comment]
Oops, that was removed in https://github.com/csvalpha/amber-ui/commit/310eba5246590ea568b8b6fce1e6c1c9f839b2cb (`app/templates/groups/index.hbs`). I think my way of thinking was "this code does nothing" as nothing changed with it gone. Is this dropdown mobile only?

**Comment by DrumsnChocolate** [comment]
Yeah, it appears to be

**Comment by DrumsnChocolate** [comment]
I can just add it back in, that should fix it
