### ISSUE TITLE
Profile pictures are not shown in news section on public page

### ISSUE THREAD

**Issue by wilco375** [csvalpha/amber-ui#57]
### How to reproduce
Go to https://csvalpha.nl/ without being logged in.

### Expected behaviour
The news section shows profile pictures.

### Current behaviour
The profile pictures are not shown.

![image](https://user-images.githubusercontent.com/7385023/68400333-2794fc00-0178-11ea-8196-8793f138f8ff.png)

**Comment by Matthijsy** [comment]
Fixed in #149
