### ISSUE TITLE
New activity form only shows up half so users cannot make new activity

### ISSUE THREAD

**Issue by Ellen-Wittingen** [csvalpha/amber-ui#587]
The new activity form only shows up half, see the image for the current issue. Because of this users cannot make new activities.
![Screenshot_20220803_154419](https://user-images.githubusercontent.com/101463776/182624255-e07fc9ee-dde8-4e89-b868-ce1d95669934.png)

I tracked it down to the module ember-file-upload being updated, which deprecated the `FileUpload` tag, which is used in `app/components/model-form/file-input.hbs` which is used for the new activity form. Their documentation shows a way to fix it under the sections "Upgrading to v5" Looking at that, I changed 
```
<FileUpload
    @name='fileUpload'
    @accept={{validMimetypes}}
    @onFileAdd={{action 'fileLoaded'}}
    @class='clickable d-block file-picker'
  >
    {{#if (get model property)}}
      <img
        id={{inputIdentifier}}
        src={{mut (get model property)}}
        alt={{label}}
      />
      <br />
    {{else}}
      <span class='image-upload-text'>
        Sleep hier een nieuwe bestand naartoe of klik om een bestand te kiezen
      </span>
    {{/if}}
  </FileUpload>
```
to
```
{{#let (file-queue name="fileUpload" onFileAdded=actions.fileLoaded) as |queue|}}
    <label for="upload-file">
      {{#if (get model property)}}
        <img id={{inputIdentifier}} src={{mut (get model property)}} alt={{label}} role="button" tabindex="0"
          aria-controls="upload-file" />
        <br />
      {{else}}
        <span class='image-upload-text' role="button" tabindex="0" aria-controls="upload-file">
          Sleep hier een nieuwe bestand naartoe of klik om een bestand te kiezen
        </span>
      {{/if}}
    </label>
    <input type="file" id="upload-file" class="" hidden accept={{validMimetypes}} {{queue.selectFile}}>
  {{/let}}
```
However, now there is a new issue where suddenly the function `this.set()` does not seem to be recognised (see image).
![Screenshot_20220803_154246](https://user-images.githubusercontent.com/101463776/182625239-3ec69068-ff25-4aa3-b7d6-803c2fcbb94a.png)

I tried to import `set` but that did not work. Then I tried to make the variables `fileTooBig` and `extensionNotPermitted` tracked to update them without `set()` but then I got other errors. I think this issue is caused by the way `onFileAdded=actions.fileLoaded` calls the action, but I do not know how to tell it to call the action `fileLoaded` with `this` properly linked. So that still needs to get fixed.

**Comment by guidojw** [comment]
I did look in the upgrade guide but not the Upgrading to v5 section, oops 😓.

Can you try

```js
onFileAdd=(action 'fileLoaded')
```

instead of 

```js
onFileAdd=actions.fileLoaded
```

Maybe it binds the context correctly then.

If not, it's probably best to revert #570 for now and come up with a fix later.

**Comment by Ellen-Wittingen** [comment]
That seems to fix it! I'll make a merge request.
