### ISSUE TITLE
Group pictures are not properly bounded

### ISSUE THREAD

**Issue by DrumsnChocolate** [csvalpha/amber-ui#615]
![image](https://user-images.githubusercontent.com/32799956/191117175-bd739656-c085-4acf-be31-26a9d5e1d591.png)
see picture. no vertical size limits
something that may help in fixing this: https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit

**Comment by palak2610** [comment]
This might also help to fix this [bug](https://developer.mozilla.org/en-US/docs/Web/CSS/max-height).
