### ISSUE TITLE
forum-post-new component does not clear contents upon cancel

### ISSUE THREAD

**Issue by DrumsnChocolate** [csvalpha/amber-ui#641]
brought up in https://github.com/csvalpha/amber-ui/pull/556#discussion_r996296640

**Comment by guidojw** [comment]
https://github.com/csvalpha/amber-ui/pull/567

**Comment by Ellen-Wittingen** [comment]
It seems fixed now? But pressing the cancel button does not clear the box and then throws errors when you do try to save after that.

**Comment by DrumsnChocolate** [comment]
On staging?
