### ISSUE TITLE
user destroy api endpoint does not exist

### ISSUE THREAD

**Issue by DrumsnChocolate** [csvalpha/amber-ui#642]
endpoint doesn't exist, but there is a destroy controller for users. What do we wanna do with this? just remove the destroy controller?
If I understand things correctly, we only archive users, never delete, right?

brought up in https://github.com/csvalpha/amber-ui/pull/556#discussion_r996299684

**Comment by wilco375** [comment]
That seems correct, yes. We might want to remove the controller, or have it trigger the archivation of the user instead.

**Comment by DrumsnChocolate** [comment]
I think we should just remove the button
