### ISSUE TITLE
English public page shows dutch content

### ISSUE THREAD

**Issue by Matthijsy** [csvalpha/amber-ui#65]
The static-pages and the articles (and their links) are in dutch on the english external page. We should consider translating this pages, or hiding them from the english external page.

**Comment by Matthijsy** [comment]
Nonfix

**Comment by wilco375** [comment]
@Matthijsy Why has this issue been closed?

**Comment by Matthijsy** [comment]
Since this is about dynamical content, and we don't think it is useful to translate all of that (then users needs to input description of an article in dutch and english)

**Comment by wilco375** [comment]
Then shouldn't we just hide the info pages in the navbar for English users like you also proposed? It's weird that when a user explicitly selects English (so he/she probably can't read Dutch), that he/she still gets Dutch content in my opinion?

**Comment by Matthijsy** [comment]
Then we actually should hide a lot of information, not only info pages but also activities, articles. That could also be weird

**Comment by wilco375** [comment]
Fair enough
