### ISSUE TITLE
Mandate create has broken breadcrumb

### ISSUE THREAD

**Issue by wilco375** [csvalpha/amber-ui#653]
### How to reproduce

Go to /debit/mandates/new

### Expected behaviour

Breadcrumb is only shown in header

### Current behaviour

Breadcrumb is also shown in content
Also, the breadcrumb is not translated fully (mandates instead of mandaten)

![image](https://user-images.githubusercontent.com/7385023/202435659-7cde3902-7003-44be-ba43-287b3b9134c7.png)

**Comment by guidojw** [comment]
I will fix in #651

**Comment by guidojw** [comment]
Fixed in https://github.com/csvalpha/amber-ui/commit/76bcd86eb1774df4c632f30be5aa95118b10b520
