### ISSUE TITLE
Old members can not modify their address

### ISSUE THREAD

**Issue by Macanazo** [csvalpha/amber-ui#802]
![Screenshot 2023-09-07 134120](https://github.com/csvalpha/amber-ui/assets/90518343/4b8ce236-e6ee-4e26-aba3-94eab2cc2836)
### How to reproduce

1. Go to profile settings as an old member and change your address

### Expected behaviour

The address should update

### Current behaviour

The address doesn't update

_Optionally add some screenshots_

**Comment by DrumsnChocolate** [comment]
this is part of #784
