### ISSUE TITLE
Show number of tagged users in photo overview

### ISSUE THREAD

**Issue by wilco375** [csvalpha/amber-ui#863]
Currently, in a photo overview (e.g. album), the number of comments on a photo are shown. It would be nice to also display the number of tags a photo has so it is clear from the overview which photos are already tagged.

**Comment by lodewiges** [comment]
this could look the same as how it looks when comment is place below a picture

**Comment by DrumsnChocolate** [comment]
#870 is related to this but not duplicate

**Comment by jegamboafuentes** [comment]
Hey @wilco375 👋

I saw your awesome issue and thought I'd let you know about [Lightning Bounties](https://www.lightningbounties.com/)! 🚀 It's a super easy-to-use app where you can add a Bitcoin reward to this issue, encouraging devs to jump in and help you solve it.

Here’s a quick tutorial to get started: [Lightning Bounties Tutorial](https://docs.lightningbounties.com/docs/posting-a-bounty/create-a-github-issue-and-submit-a-new-reward). 💡 You can post your issue there, set up a bounty, and whoever cracks the code gets rewarded instantly in Bitcoin. 🔥

Let me know if you have any questions or need help setting it up!

Cheers! ⚡
