### ISSUE TITLE
Update sog page

### ISSUE THREAD

**Issue by wilco375** [csvalpha/amber-ui#864]
We could update the SOG page with links to more activities users could do to SOG, e.g. tagging of images.

**Comment by lodewiges** [comment]
maybe it is an idea to redirect people to the most recent picture without anytags so they have a place to start for the tagging feature

**Comment by wilco375** [comment]
> maybe it is an idea to redirect people to the most recent picture without anytags so they have a place to start for the tagging feature
> 

I was thinking of just throwing them to the album overview page, but that's also possible. Not a great solution maybe in case that picture has no people in it though

**Comment by lodewiges** [comment]
i had the same problem if there are no people, maybe add a tag that there is nobody. however, it would make it easier in the future to find a photo that still needs tags

**Comment by wilco375** [comment]
For now I'm showing albums in which none of the photos have tags on the SOG page. Once the overview of albums and photos also shows whether tags are present (#863, #870), this is less of an issue anyways.
